// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: errdefs.proto

package errdefs

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	pb "github.com/khulnasoft/devkit/solver/pb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Vertex struct {
	Digest               string   `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vertex) Reset()         { *m = Vertex{} }
func (m *Vertex) String() string { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()    {}
func (*Vertex) Descriptor() ([]byte, []int) {
	return fileDescriptor_689dc58a5060aff5, []int{0}
}
func (m *Vertex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vertex.Unmarshal(m, b)
}
func (m *Vertex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vertex.Marshal(b, m, deterministic)
}
func (m *Vertex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vertex.Merge(m, src)
}
func (m *Vertex) XXX_Size() int {
	return xxx_messageInfo_Vertex.Size(m)
}
func (m *Vertex) XXX_DiscardUnknown() {
	xxx_messageInfo_Vertex.DiscardUnknown(m)
}

var xxx_messageInfo_Vertex proto.InternalMessageInfo

func (m *Vertex) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

type Source struct {
	Info                 *pb.SourceInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Ranges               []*pb.Range    `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_689dc58a5060aff5, []int{1}
}
func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetInfo() *pb.SourceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Source) GetRanges() []*pb.Range {
	if m != nil {
		return m.Ranges
	}
	return nil
}

type FrontendCap struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrontendCap) Reset()         { *m = FrontendCap{} }
func (m *FrontendCap) String() string { return proto.CompactTextString(m) }
func (*FrontendCap) ProtoMessage()    {}
func (*FrontendCap) Descriptor() ([]byte, []int) {
	return fileDescriptor_689dc58a5060aff5, []int{2}
}
func (m *FrontendCap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontendCap.Unmarshal(m, b)
}
func (m *FrontendCap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontendCap.Marshal(b, m, deterministic)
}
func (m *FrontendCap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontendCap.Merge(m, src)
}
func (m *FrontendCap) XXX_Size() int {
	return xxx_messageInfo_FrontendCap.Size(m)
}
func (m *FrontendCap) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontendCap.DiscardUnknown(m)
}

var xxx_messageInfo_FrontendCap proto.InternalMessageInfo

func (m *FrontendCap) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Subrequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subrequest) Reset()         { *m = Subrequest{} }
func (m *Subrequest) String() string { return proto.CompactTextString(m) }
func (*Subrequest) ProtoMessage()    {}
func (*Subrequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_689dc58a5060aff5, []int{3}
}
func (m *Subrequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subrequest.Unmarshal(m, b)
}
func (m *Subrequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subrequest.Marshal(b, m, deterministic)
}
func (m *Subrequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subrequest.Merge(m, src)
}
func (m *Subrequest) XXX_Size() int {
	return xxx_messageInfo_Subrequest.Size(m)
}
func (m *Subrequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Subrequest.DiscardUnknown(m)
}

var xxx_messageInfo_Subrequest proto.InternalMessageInfo

func (m *Subrequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Solve struct {
	InputIDs []string `protobuf:"bytes,1,rep,name=inputIDs,proto3" json:"inputIDs,omitempty"`
	MountIDs []string `protobuf:"bytes,2,rep,name=mountIDs,proto3" json:"mountIDs,omitempty"`
	Op       *pb.Op   `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	// Types that are valid to be assigned to Subject:
	//
	//	*Solve_File
	//	*Solve_Cache
	Subject              isSolve_Subject `protobuf_oneof:"subject"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Solve) Reset()         { *m = Solve{} }
func (m *Solve) String() string { return proto.CompactTextString(m) }
func (*Solve) ProtoMessage()    {}
func (*Solve) Descriptor() ([]byte, []int) {
	return fileDescriptor_689dc58a5060aff5, []int{4}
}
func (m *Solve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Solve.Unmarshal(m, b)
}
func (m *Solve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Solve.Marshal(b, m, deterministic)
}
func (m *Solve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Solve.Merge(m, src)
}
func (m *Solve) XXX_Size() int {
	return xxx_messageInfo_Solve.Size(m)
}
func (m *Solve) XXX_DiscardUnknown() {
	xxx_messageInfo_Solve.DiscardUnknown(m)
}

var xxx_messageInfo_Solve proto.InternalMessageInfo

type isSolve_Subject interface {
	isSolve_Subject()
}

type Solve_File struct {
	File *FileAction `protobuf:"bytes,4,opt,name=file,proto3,oneof" json:"file,omitempty"`
}
type Solve_Cache struct {
	Cache *ContentCache `protobuf:"bytes,5,opt,name=cache,proto3,oneof" json:"cache,omitempty"`
}

func (*Solve_File) isSolve_Subject()  {}
func (*Solve_Cache) isSolve_Subject() {}

func (m *Solve) GetSubject() isSolve_Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *Solve) GetInputIDs() []string {
	if m != nil {
		return m.InputIDs
	}
	return nil
}

func (m *Solve) GetMountIDs() []string {
	if m != nil {
		return m.MountIDs
	}
	return nil
}

func (m *Solve) GetOp() *pb.Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *Solve) GetFile() *FileAction {
	if x, ok := m.GetSubject().(*Solve_File); ok {
		return x.File
	}
	return nil
}

func (m *Solve) GetCache() *ContentCache {
	if x, ok := m.GetSubject().(*Solve_Cache); ok {
		return x.Cache
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Solve) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Solve_File)(nil),
		(*Solve_Cache)(nil),
	}
}

type FileAction struct {
	// Index of the file action that failed the exec.
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileAction) Reset()         { *m = FileAction{} }
func (m *FileAction) String() string { return proto.CompactTextString(m) }
func (*FileAction) ProtoMessage()    {}
func (*FileAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_689dc58a5060aff5, []int{5}
}
func (m *FileAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileAction.Unmarshal(m, b)
}
func (m *FileAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileAction.Marshal(b, m, deterministic)
}
func (m *FileAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileAction.Merge(m, src)
}
func (m *FileAction) XXX_Size() int {
	return xxx_messageInfo_FileAction.Size(m)
}
func (m *FileAction) XXX_DiscardUnknown() {
	xxx_messageInfo_FileAction.DiscardUnknown(m)
}

var xxx_messageInfo_FileAction proto.InternalMessageInfo

func (m *FileAction) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ContentCache struct {
	// Original index of result that failed the slow cache calculation.
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentCache) Reset()         { *m = ContentCache{} }
func (m *ContentCache) String() string { return proto.CompactTextString(m) }
func (*ContentCache) ProtoMessage()    {}
func (*ContentCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_689dc58a5060aff5, []int{6}
}
func (m *ContentCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentCache.Unmarshal(m, b)
}
func (m *ContentCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentCache.Marshal(b, m, deterministic)
}
func (m *ContentCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentCache.Merge(m, src)
}
func (m *ContentCache) XXX_Size() int {
	return xxx_messageInfo_ContentCache.Size(m)
}
func (m *ContentCache) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentCache.DiscardUnknown(m)
}

var xxx_messageInfo_ContentCache proto.InternalMessageInfo

func (m *ContentCache) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*Vertex)(nil), "errdefs.Vertex")
	proto.RegisterType((*Source)(nil), "errdefs.Source")
	proto.RegisterType((*FrontendCap)(nil), "errdefs.FrontendCap")
	proto.RegisterType((*Subrequest)(nil), "errdefs.Subrequest")
	proto.RegisterType((*Solve)(nil), "errdefs.Solve")
	proto.RegisterType((*FileAction)(nil), "errdefs.FileAction")
	proto.RegisterType((*ContentCache)(nil), "errdefs.ContentCache")
}

func init() { proto.RegisterFile("errdefs.proto", fileDescriptor_689dc58a5060aff5) }

var fileDescriptor_689dc58a5060aff5 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x86, 0x27, 0xd7, 0x21, 0xa7, 0xc0, 0xc2, 0xc0, 0x28, 0x9a, 0x55, 0xc6, 0x62, 0x51, 0x16,
	0x24, 0x68, 0x78, 0x02, 0x28, 0x1a, 0xcd, 0xac, 0x2a, 0xb9, 0x12, 0xfb, 0x5c, 0x4e, 0x5a, 0xd3,
	0xd4, 0x36, 0xbe, 0x54, 0x7d, 0x38, 0x1e, 0x0e, 0xc5, 0x49, 0x0b, 0x8b, 0xee, 0xf2, 0xe7, 0xfb,
	0x7c, 0xec, 0xdf, 0x86, 0x37, 0xa8, 0x75, 0x87, 0xbd, 0x29, 0x95, 0x96, 0x56, 0x92, 0xdb, 0x39,
	0xde, 0x7f, 0xd9, 0x72, 0xbb, 0x73, 0x4d, 0xd9, 0xca, 0x43, 0xb5, 0xdf, 0xb9, 0x41, 0xd4, 0x46,
	0xf6, 0xb6, 0xea, 0xf0, 0xb8, 0xe7, 0xb6, 0x32, 0x72, 0x38, 0xa2, 0xae, 0x54, 0x53, 0x49, 0x35,
	0x2f, 0xa5, 0x05, 0xa4, 0x3f, 0x51, 0x5b, 0x3c, 0x91, 0x3b, 0x48, 0x3b, 0xbe, 0x45, 0x63, 0xf3,
	0xa0, 0x08, 0x96, 0x19, 0x9b, 0x13, 0x5d, 0x43, 0xba, 0x91, 0x4e, 0xb7, 0x48, 0x28, 0xc4, 0x5c,
	0xf4, 0xd2, 0xf3, 0xc5, 0xe3, 0xdb, 0x52, 0x35, 0xe5, 0x44, 0x5e, 0x44, 0x2f, 0x99, 0x67, 0xe4,
	0x01, 0x52, 0x5d, 0x8b, 0x2d, 0x9a, 0x3c, 0x2c, 0xa2, 0xe5, 0xe2, 0x31, 0x1b, 0x2d, 0x36, 0xfe,
	0x61, 0x33, 0xa0, 0x0f, 0xb0, 0x78, 0xd2, 0x52, 0x58, 0x14, 0xdd, 0xaa, 0x56, 0x84, 0x40, 0x2c,
	0xea, 0x03, 0xce, 0xbb, 0xfa, 0x6f, 0x5a, 0x00, 0x6c, 0x5c, 0xa3, 0xf1, 0xb7, 0x43, 0x63, 0xaf,
	0x1a, 0x7f, 0x02, 0x48, 0x36, 0x63, 0x1f, 0x72, 0x0f, 0xaf, 0xb8, 0x50, 0xce, 0xbe, 0xfc, 0x30,
	0x79, 0x50, 0x44, 0xcb, 0x8c, 0x5d, 0xf2, 0xc8, 0x0e, 0xd2, 0x09, 0xcf, 0xc2, 0x89, 0x9d, 0x33,
	0xb9, 0x83, 0x50, 0xaa, 0x3c, 0xf2, 0x5d, 0xd2, 0xf1, 0x94, 0x6b, 0xc5, 0x42, 0xa9, 0xc8, 0x27,
	0x88, 0x7b, 0x3e, 0x60, 0x1e, 0x7b, 0xf2, 0xae, 0x3c, 0x5f, 0xf5, 0x13, 0x1f, 0xf0, 0x5b, 0x6b,
	0xb9, 0x14, 0xcf, 0x37, 0xcc, 0x2b, 0xe4, 0x33, 0x24, 0x6d, 0xdd, 0xee, 0x30, 0x4f, 0xbc, 0xfb,
	0xe1, 0xe2, 0xae, 0x7c, 0x3d, 0xbb, 0x1a, 0xe1, 0xf3, 0x0d, 0x9b, 0xac, 0xef, 0x19, 0xdc, 0x1a,
	0xd7, 0xfc, 0xc2, 0xd6, 0x52, 0x0a, 0xf0, 0x6f, 0x1e, 0x79, 0x0f, 0x09, 0x17, 0x1d, 0x9e, 0x7c,
	0xc3, 0x88, 0x4d, 0x81, 0x7e, 0x84, 0xd7, 0xff, 0xcf, 0xb9, 0x6e, 0x35, 0xa9, 0x7f, 0xc7, 0xaf,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xe9, 0x8c, 0xe5, 0x13, 0x02, 0x00, 0x00,
}
