name: devkit
services:
  devkit:
    container_name: devkit-dev
    build:
      context: ../..
      args:
        DEVKIT_DEBUG: 1
    image: khulnasoft/devkit:local
    ports:
      - 127.0.0.1:1234:1234
      - 127.0.0.1:5000:5000
      - 127.0.0.1:6060:6060
    restart: always
    privileged: true
    environment:
      DELVE_PORT: 5000
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317
    configs:
      - source: devkit_config
        target: /etc/devkit/devkitd.toml
    volumes:
      - devkit:/var/lib/devkit

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 127.0.0.1:16686:16686

volumes:
  devkit:

configs:
  devkit_config:
    file: ./devkitd.toml
