apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devkitd
  name: devkitd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devkitd
  template:
    metadata:
      labels:
        app: devkitd
    spec:
      containers:
        - name: devkitd
          image: khulnasoft/devkit:master
          args:
            - --addr
            - unix:///run/devkit/devkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --tlscacert
            - /certs/ca.pem
            - --tlscert
            - /certs/cert.pem
            - --tlskey
            - /certs/key.pem
          # the probe below will only work after Release v0.6.3
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          # the probe below will only work after Release v0.6.3
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
          ports:
            - containerPort: 1234
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
      volumes:
        # devkit-daemon-certs must contain ca.pem, cert.pem, and key.pem
        - name: certs
          secret:
            secretName: devkit-daemon-certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devkitd
  name: devkitd
spec:
  ports:
    - port: 1234
      protocol: TCP
  selector:
    app: devkitd
