apiVersion: v1
kind: Pod
metadata:
  name: devkitd
spec:
  containers:
    - name: devkitd
      image: khulnasoft/devkit:master
      readinessProbe:
        exec:
          command:
            - buildctl
            - debug
            - workers
        initialDelaySeconds: 5
        periodSeconds: 30
      livenessProbe:
        exec:
          command:
            - buildctl
            - debug
            - workers
        initialDelaySeconds: 5
        periodSeconds: 30
      securityContext:
        privileged: true
