apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: devkitd
  name: devkitd
spec:
  serviceName: devkitd
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: devkitd
  template:
    metadata:
      labels:
        app: devkitd
    spec:
      containers:
        - name: devkitd
          image: khulnasoft/devkit:master
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
