apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: devkitd
  name: devkitd
spec:
  serviceName: devkitd
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: devkitd
  template:
    metadata:
      labels:
        app: devkitd
      annotations:
        container.apparmor.security.beta.kubernetes.io/devkitd: unconfined
    # see devkit/docs/rootless.md for caveats of rootless mode
    spec:
      containers:
        - name: devkitd
          image: khulnasoft/devkit:master-rootless
          args:
            - --oci-worker-no-process-sandbox
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            # Needs Kubernetes >= 1.19
            seccompProfile:
              type: Unconfined
            # To change UID/GID, you need to rebuild the image
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            # Dockerfile has `VOLUME /home/user/.local/share/devkit` by default too,
            # but the default VOLUME does not work with rootless on Google's Container-Optimized OS
            # as it is mounted with `nosuid,nodev`.
            # https://github.com/khulnasoft/devkit/issues/879#issuecomment-1240347038
            - mountPath: /home/user/.local/share/devkit
              name: devkitd
      volumes:
        - name: devkitd
          emptyDir: {}
